# Generated by Django 3.0.7 on 2020-11-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0002_auto_20201106_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='condicion_paquete',
            field=models.ManyToManyField(blank=True, null=True, to='Reservacion.Condicion', verbose_name='Condiciones'),
        ),
    ]
