# Generated by Django 3.0.7 on 2020-11-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0004_auto_20201106_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fechaEntradaReservacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Entrada '),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fechaRegistroReservacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fechaSalidaReservacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Salida'),
        ),
    ]
