# Generated by Django 3.0.7 on 2020-11-09 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0005_auto_20201106_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='fechaRegistroReservacion',
            new_name='fechaViajeReservacion',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='fechaEntradaReservacion',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='fechaSalidaReservacion',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='adultosReservacion',
            field=models.CharField(blank=True, choices=[('0', '0 '), ('1', '1 '), ('2', '2 '), ('3', '3 '), ('4', '4 '), ('5', '5 '), ('6', '6 '), ('7', '7 '), ('8', '8 '), ('9', '9 '), ('10', '10 ')], default='0', max_length=2, verbose_name='Cantidad de adultos'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='cantidadDiasReservacion',
            field=models.PositiveSmallIntegerField(blank=True, default=150, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Cantidad de Dias'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='niñosReservacion',
            field=models.CharField(blank=True, choices=[('0', '0 '), ('1', '1 '), ('2', '2 '), ('3', '3 '), ('4', '4 '), ('5', '5 '), ('6', '6 '), ('7', '7 '), ('8', '8 '), ('9', '9 '), ('10', '10 ')], default='0', max_length=2, verbose_name='Cantidad de niños'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='disponibilidadPaquete',
            field=models.PositiveSmallIntegerField(blank=True, default=150, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Numero de Cupos'),
        ),
    ]
