# Generated by Django 3.0.7 on 2020-11-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0006_auto_20201108_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='reservacion_paquete',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='paquete_reservacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservacion.Paquete'),
        ),
        migrations.DeleteModel(
            name='ViajeContratado',
        ),
    ]
