# Generated by Django 3.0.7 on 2020-11-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0007_auto_20201108_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='paquete_reservacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservacion.Paquete', verbose_name='Destino'),
        ),
    ]
