# Generated by Django 3.0.7 on 2020-11-14 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0009_auto_20201112_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='cuposReservacion',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Cupos (Personas)'),
        ),
    ]
