# Generated by Django 3.0.7 on 2020-11-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0012_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='fechaCreacionRating',
        ),
    ]
