# Generated by Django 3.0.7 on 2020-11-15 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0013_remove_rating_fechacreacionrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='paquete_Rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservacion.Paquete'),
        ),
    ]
