# Generated by Django 3.0.7 on 2020-11-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0017_reservacion_usuario_reservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='fechaCreacionPaquete',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
