# Generated by Django 3.0.7 on 2020-11-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0022_auto_20201122_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicion',
            name='tituloCondicion',
            field=models.CharField(blank=True, choices=[('i', 'Incluida '), ('n', 'No Incluida ')], max_length=1, null=True, verbose_name='Tipo de Condicion'),
        ),
    ]
