# Generated by Django 3.0.7 on 2020-11-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0024_auto_20201122_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='condicion_paquete',
        ),
        migrations.AddField(
            model_name='condicion',
            name='paquete_condicion',
            field=models.ManyToManyField(to='Reservacion.Paquete', verbose_name='Tags'),
        ),
    ]
