# Generated by Django 3.0.7 on 2020-11-23 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0025_auto_20201122_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='paquete_usuario',
        ),
        migrations.AddField(
            model_name='rating',
            name='paquete_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservacion.Paquete'),
        ),
        migrations.AddField(
            model_name='rating',
            name='usuario_Rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
