# Generated by Django 3.0.7 on 2020-11-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0026_auto_20201122_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='paquete_rating',
        ),
    ]
