# Generated by Django 3.0.7 on 2020-11-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0027_remove_rating_paquete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='paquete_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservacion.Paquete'),
        ),
    ]
