# Generated by Django 3.0.7 on 2020-11-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0029_auto_20201124_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicion',
            name='paquete_condicion',
        ),
        migrations.AddField(
            model_name='paquete',
            name='condicion_paquete',
            field=models.ManyToManyField(to='Reservacion.Condicion', verbose_name='Condiciones'),
        ),
    ]
