# Generated by Django 3.1.3 on 2020-11-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0031_auto_20201127_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('idMes', models.AutoField(help_text='ID único para esta Mes', primary_key=True, serialize=False)),
                ('tituloMes', models.CharField(max_length=200, verbose_name='Nombre')),
                ('estadoMes', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
