# Generated by Django 3.1.3 on 2020-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0032_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='mes_paquete',
            field=models.ManyToManyField(to='Reservacion.Mes', verbose_name='Meses'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='mesPaquete',
            field=models.CharField(blank=True, choices=[('Especificar', 'Especificar'), ('Todos los meses', 'Todos los meses')], default='Todos los meses', max_length=15, null=True, verbose_name='Mes de Disponiblidad'),
        ),
    ]
