# Generated by Django 3.1.3 on 2020-12-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0034_visitausuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
